[build]
builder = "DOCKERFILE"
dockerfilePath = "back/Dockerfile"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "signify-backend"
port = 8765
protocol = "TCP"