[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
rootDirectory = "back"

[deploy]
startCommand = "uv run python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "signify-backend"
port = 8765
protocol = "TCP"