[project]
name = "back"
version = "0.1.0"
description = "Add your description here"
readme = ""
requires-python = ">=3.11"
dependencies = [
    "mediapipe==0.10.21",
    "numpy==1.26.4",
    "opencv-python-headless==4.11.0.86",
    "torch==2.9.1",
    "websockets==15.0.1",
]
